/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_dnndkfilesplit_MainActivity */

#ifndef _Included_com_example_administrator_dnndkfilesplit_MainActivity
#define _Included_com_example_administrator_dnndkfilesplit_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_dnndkfilesplit_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_dnndkfilesplit_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_administrator_dnndkfilesplit_MainActivity
 * Method:    accessLocalMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_dnndkfilesplit_MainActivity_accessLocalMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
